#!/bin/bash
# Lkcars Installer

install()
{

dir="/tmp"
cd $dir  || return

wget https://raw.githubusercontent.com/Tearran/lkars/master/liblkars
sudo cp liblkars /usr/lib/

wget https://raw.githubusercontent.com/Tearran/lkars/master/lkars-config
sudo cp lkars-config /usr/bin/
sudo chmod +x /usr/bin/lkars-config

wget https://github.com/Tearran/iic-scanner/raw/main/iic-scanner
sudo cp iic-scanner /usr/bin/
sudo chmod +x /usr/bin/iic-scanner

}

uninstall()
{

sudo rm -f  /usr/lib/liblkars.0
sudo rm -f  /usr/bin/lkars-config
sudo rm -f  /usr/bin/iic-scanner
echo "uninstall complete!"

}

dev()
{

echo
echo "TODO"
echo

}

Vers()
{

   echo "LKARS Installer."
   echo
   echo "Software version: pre-Alpha."
   echo

}

Help()
{

   echo "LKARS Installer."
   echo
   echo "Syntax:  [-hviu]"
   echo "Options:"
   echo "-i     Install lkars-config"
   echo "-u     Uninstall lkars-config"
   echo "-h     Print this Help."
   echo "-v     Print Version info."

}

if [[ $# -eq 0 ]] ; then
    install
    exit 1
fi

while getopts ":hviud" opt; do
   case $opt in
      h) Help break ;;
      v) Vers break ;;
      i) install break ;;
      u) uninstall break ;;
      ?) Help break ;;
   esac
exit
done
