#!/usr/bin/env bash
#LKARS="$HOME/.local"

Help()
{
   echo "LKARS Installer."
   echo
   echo "Syntax:  [-hviu]"
   echo "Options:"
   echo "l     list liblkars Funcions"
   echo "h     Print this Help."
   echo "v     Print Version info."
}

fun_csv=$( grep '.*(){' '/lib/liblkars' | sed -z 's|(){| |g;s|\n|,|g;s|,$|\n|' )
while getopts ":hlv" opt; do
   case $opt in
      h) Help exit ;;
      l) echo $fun_csv exit ;;
      v) echo "v 0.0.0???" exit ;;
      ?) Help exit ;;
   esac
exit
done
