#!/bin/bash
# lkars-config

clear
source "/usr/lib/liblkars.0"
[ ! -f /usr/lib/liblkars.0 ]  &&   echo "liblkars.0 NOT found"


menu_main(){
  menu=("1" "Install App" "2" "Check Sensors" "9" "Development" "0" "Reboot")
  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Finish  --menu "Make your choice" 25 50 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
    case $CHOICE in
        "1") menu_apps ;;
        "2") [ -f /usr/bin/iic-get ] && iic-get 1 ;;
        "9") menu_dev ;;
        "0") sudo reboot ;;
         *) exit ;;
    esac
}

menu_display(){
  menu=("1" "ST7735SW" "2" "Pirate audio phat" "3" "Restore System Default")
  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" 25 50 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
      case "$CHOICE" in
        "1") build_st7735sw_fbcp && 128x160_bootconfig && fbcpd_systemctl;;
        "2") build_pirate_audio_fbcp && 240x240_bootconfig && fbcpd_systemctl ;;
        "3") default_bootconfig && ( sudo systemctl disable fbcpd ) ;;
      esac
      return 0
}

menu_dev(){
  menu=("1" "ST7735SW" "2" "Pirate audio phat" "3" "Restore System Default")
  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" 25 50 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
      case "$CHOICE" in
        "1") build_st7735sw_fbcp && 128x160_bootconfig && fbcpd_systemctl;;
        "2") build_pirate_audio_fbcp && 240x240_bootconfig && fbcpd_systemctl ;;
        "3") default_bootconfig && ( sudo systemctl disable fbcpd ) ;;
      esac
      return 0
}

menu_apps(){
  menu=("1" "Download Source" "2" "Virtual environment" "3" "Samba file share")
  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" 25 50 9 "${menu[@]}"  3>&2 2>&1 1>&3 )

      case "$CHOICE" in
        "1") get_src ;;
        "2") set_vertenv ;;
        "3") set_samba ;;
      esac
      return 0
}

menu_samba(){
  menu=("1" "Download Source" "2" "Virtual environment" "3" "Samba file share")
  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" 25 50 9 "${menu[@]}"  3>&2 2>&1 1>&3 )

      case "$CHOICE" in
        "1") get_src ;;
        "2") set_vertenv ;;
        "3") set_samba ;;
      esac
      return 0
}
while true ;
 do
   menu_main
 done
