#!/bin/bash
# lkars-config

clear

export NEWT_COLORS='
root=white,black
window=white,black
textbox=green,black
title=green,black
listbox=yellow,black
sellistbox=black,green
actsellistbox=black,yellow
border=blue,black
actbutton=black,green
'

if [  -f /usr/lib/liblkars ] ;
then
source "/usr/lib/liblkars"
else
  srcdir="$(dirname $0)"
  srcdir="$(cd $srcdir && pwd)"
  source "$srcdir/liblkars"
  echo "dev Mode"
fi

use_iic(){
x=$( ls /dev/i2c* ) ; [[ $x != */dev/i2c-* ]] && sudo raspi-config nonint do_i2c 0 ; iic-scanner 1
}

menu_main(){
  menu=("1" "Aplications" "9" "Development" "0" "Reboot")
  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Finish  --menu "Make your choice" $(stty size) 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
    case $CHOICE in
        "1") menu_apps ;;
        "9") menu_dev ;;
        "0") sudo reboot ;;
         *) exit ;;
    esac
}

menu_iic(){
  menu=("1" "Scan IIC devices" "2" "Pinout guide" )
  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" $(stty size) 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
      case "$CHOICE" in
        "1") ( use_iic ; i=$( iic-scanner 1 )  ;  whiptail --msgbox "$i"  0 0 --scrolltext );;
        "2") ( i=$( pinout    ) ; whiptail --msgbox "$i"  0 0 --scrolltext ) ;;
      esac
      return 0

}

menu_display(){
  menu=("1" "ST7735SW" "2" "Pirate audio phat" "3" "Restore System Default")
  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" $(stty size) 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
      case "$CHOICE" in
        "1") build_st7735sw_fbcp && 128x160_bootconfig && fbcpd_systemctl;;
        "2") build_pirate_audio_fbcp && 240x240_bootconfig && fbcpd_systemctl ;;
        "3") default_bootconfig && ( sudo systemctl disable fbcpd ) ;;
      esac
      return 0
}

menu_dev(){
  menu=("1" "Displays" "2" "iic Tools" "3" "Virtual environment" "4" "Setup file share" "5" "Download LKARS Source")
  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" $(stty size) 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
      case "$CHOICE" in
        "1") menu_display;;
        "2") menu_iic;;
        "3") set_vertenv ;;
        "4") set_samba ;;
        "5") get_src ;;
      esac
      return 0
}

menu_apps(){
  menu=("LKARS" "Sorce code for LKARS" \
  "picorderOS" "Sorce code for picorderOS" \
  "sense_hat_demo" "8x8 matrix demo for the sence hat -python3"\
  "python_skelly" "skelliton app for single file deplyment -python3")
  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" $(stty size) 9 "${menu[@]}"  3>&2 2>&1 1>&3 )

      case "$CHOICE" in
        "LKARS") get_src lkars;;
        "picorderOS") get_src picorderOS;;
        "sense_hat_demo") get_src sense_hat_demo ;;
        "python_skelly") get_src python_skelly ;;
      esac
      return 0
}


while true ;
 do
   menu_main
 done
