#!/bin/bash

#Uncomment set -x to debug (see bash output to assist manual debug)
#set -x
clear
#Ver format stable.unstable.testing
# versinfo="0.0.1" first alpha
# versinfo="0.1.0" first release
# versinfo="1.0.0" first stable release
versinfo="0.1.1"

#Distrabution Compatibility check
[[ -f /bin/raspi-config ]] && distro_congfig="raspi"
[[ -f /usr/bin/armbian-config ]] && distro_congfig="armbian"

#File location and name 
SRC="${BASH_SOURCE[0]}"

#Enable Dynamic directory root ~/ or /bin or /usr/sbin etc.. 
DIRECTORY=$(cd $(dirname "$0") && pwd)

# The name of the File without the leading path
filename=$(basename "$SRC")

#Path to librarie if installed /user/lib/ (system mode)
[ -f /usr/lib/its-lib ] && libname=/user/lib/its-lib

#path to library if not installed ( dev/user mode)
[ ! -f /usr/lib/its-lib ] && libname=$(dirname "$0")/its-lib

#include library
[ -f "$libname" ] && . "$libname"

# Newt color theme for whiptail
[ -f "$(dirname "$0")/its/theme/theme" ] && source "$(dirname "$0")/its/theme/theme"
#Menu Generation
#read, sort and and filter data
run_whiptail()
{
  #Consol size used for whiptail
  #alternitive $(stty size)
  cols=$(tput cols)
  rows=20 #$(tput lines)
  
  # Generate a Catigory array
  readarray -t cat_array < <( grep -e '^##.*' "$libname" | sed "s|^##||g;s| ##.*||g" | sort -u )
  
  # loop and number catagory array 
  readarray -t cat_loop < <( for i in "${!cat_array[@]}" ; do  printf "%s\n %s\n"  "$i" "${cat_array[i]}" ; done )
  
end=0
while :
  do
	clear
    # Display Main\Catagory menu 
    cat_result=$(whiptail --title  "${filename%.*}" --cancel-button Finish --menu --clear " " "$rows" "$cols" "$end" "${cat_loop[@]}" 3>&2 2>&1 1>&3- )
    
    # if none selected or --cancel-button pressed, do nothing and exit
    [[ -z $cat_result ]] && exit 
    
    # else create Sub menu decriptions     
    [[ -n $cat_result ]] && readarray -t grp_array < <( grep -e "${cat_array[$cat_result]}" "$libname" | sed "s|^##||g;s| ##| |g;s|${cat_array[$cat_result]}||g;s|( distro-congfig )|( ${distro_congfig[*]} )|g" ) && echo "${grp_array[@]}"
    # Loop it 
    [[ -n $cat_result ]] && readarray -t dis_loop < <( for i in "${!grp_array[@]}" ; do  printf "%s\n%s\n"  "$i" "${grp_array[i]}" ; done )
    
    #Display Sub Menu 
    dis_result=$(whiptail --title  "${filename%.*}" --cancel-button Back --menu --clear " " "$rows" "$cols" "$end" "${dis_loop[@]}" 3>&2 2>&1 1>&3- )
    
    # if selected find selected Sub menu function 
    [[ -n $dis_result ]] && readarray -t fun_array < <( grep -B1 "${cat_array[$cat_result]}" "$libname" | sed -z 's|(){\n||g;s|--\n||g' ) 
    # Loop it
    [[ -n $dis_result ]] && readarray -t fun_loop < <( for i in "${!fun_array[@]}" ; do  printf "%s\n" "${fun_array[i]}" | sed -z 's|##.*##||g' ; done )

    # if selected Excute selected Sub menu function
    [[ -n $dis_result ]] && "${fun_loop[$dis_result]}"

    # else end of loop and restart
  done

}

see_version()
{
  echo " ${filename%.*} version $versinfo "
}

make_ifts()
{
  #Library file name
  itsname=its-lib  
  #Check for lkars-its library if not found generate its
  if ( whiptail --title  "${filename%.*}" --yesno  "\nGenerating requered Library?\n\n" 0 0  ) ; then
  #Contributor spacific scripts   
  [[ -d "$DIRECTORY"/its/other ]] && cat $( echo -e "$DIRECTORY"/its/other/*.its )  >  "$DIRECTORY"/$itsname
  [[ -d "$DIRECTORY"/its/picorder ]] && cat $( echo -e "$DIRECTORY"/its/picorder/*.its )  >>  "$DIRECTORY"/$itsname
  #distrabution spacific scripts 
  [[ -d "$DIRECTORY"/its/"${distro_congfig}"/ ]] && cat $( echo -e "$DIRECTORY"/its/"${distro_congfig}"/*.its )  >>  "$DIRECTORY"/$itsname
 
  #Compleed message
  bla=$( printf '\nLibrary Generation complete\n\tSystem set for %s \n\n\nPress OK to continue...' "${distro_congfig}" ) 
  whiptail --title  "${filename%.*}" --msgbox "${bla}" 0 0
fi

}



#Generated library
[[ $# -eq 0 ]] && ( ( [ -f "$libname" ] && run_whiptail ) || ( make_ifts ) )

see_help()
{
  echo "Usage: ${filename%.*} [ -h  | -v | -m ]"
  echo -e "Options:"
  echo -e "\t-h\tPrint this help."
  echo -e "\t-v\tPrint version info."
  echo -e "\t-m\tGenerate library.\n"
}

#Help info
if [[ $# -eq 1 ]] ; then
while getopts ":hvm" opt; do
    case $opt in
      h) see_help break ;;
      v) see_version break ;;
      m) ( make_ifts  ) ; break ;; #Re-Generated library
      ?) echo  -e "\033[33;5m?! Say What!?\033[0m" ; see_help break ;;
    esac
  exit
done
fi
